/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseCard: typeof import('./src/components/BaseCard.vue')['default']
    BaseCharts: typeof import('./src/components/BaseCharts.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    PoliceList: typeof import('./src/components/PoliceList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TransitionLeftBox: typeof import('./src/components/TransitionLeftBox.vue')['default']
    TransitionRightBox: typeof import('./src/components/TransitionRightBox.vue')['default']
    VideoItem: typeof import('./src/components/VideoItem.vue')['default']
  }
}
