/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/02': RouteRecordInfo<'/02', '/02', Record<never, never>, Record<never, never>>,
    '/03': RouteRecordInfo<'/03', '/03', Record<never, never>, Record<never, never>>,
    '/04': RouteRecordInfo<'/04', '/04', Record<never, never>, Record<never, never>>,
    '/05': RouteRecordInfo<'/05', '/05', Record<never, never>, Record<never, never>>,
  }
}
